name: Samurai GPU test with Beltrami

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: [self-hosted, Linux, X64]

    steps:
    - uses: actions/checkout@v3
    - name: Build the apptainer image
      run: apptainer build --nv samurai_nvhpc.sif apptainer.def
    - name: Running the apptainer image for Beltrami case
      run: apptainer run --nv samurai_nvhpc.sif
