name: Samurai CPU test with Beltrami

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: [self-hosted, Linux, X64]

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag samurai_build_run:latest
    - name: Running the Docker image for Beltrami case
      run: docker run samurai_build_run:latest
